### ISSUE TITLE
Add support for macOS

### ISSUE THREAD

**Issue by paltdariusz** [iboxdb/db4o-gpl#1]
While creating a new db object the error "System.PlatformNotSupportedException: Locking/unlocking file regions is not supported on this platform. Use FileShare on this entire file instead." occurs.

Line of code making this error:
`Db4oEmbedded.OpenFile(Db4oEmbedded.NewConfiguration(), "db");` 

Error traceback: 
`  at System.IO.Strategies.OSFileStreamStrategy.Lock(Int64 position, Int64 length)
   at Db4objects.Db4o.Internal.Platform4.LockFile(String path, Object file)
   at Db4objects.Db4o.IO.RandomAccessFileFactory.NewRandomAccessFile(String path, Boolean readOnly, Boolean lockFile)
   at Db4objects.Db4o.IO.FileStorage.FileBin..ctor(BinConfiguration config)
   at Db4objects.Db4o.IO.FileStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.StorageDecorator.Open(BinConfiguration config)
   at Db4objects.Db4o.IO.CachingStorage.Open(BinConfiguration config)
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer.OpenImpl()
   at Db4objects.Db4o.Internal.ObjectContainerBase._IRunnable_129.Run()
   at Db4objects.Db4o.Foundation.DynamicVariable.With(Object value, IRunnable block)
   at Db4objects.Db4o.Foundation.Environments.RunWith(IEnvironment environment, IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.WithEnvironment(IRunnable runnable)
   at Db4objects.Db4o.Internal.ObjectContainerBase.Open()
   at Db4objects.Db4o.Internal.IoAdaptedObjectContainer..ctor(IConfiguration config, String fileName)
   at Db4objects.Db4o.Internal.ObjectContainerFactory.OpenObjectContainer(IEmbeddedConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oEmbedded.OpenFile(IEmbeddedConfiguration config, String databaseFileName)
   at Db4objects.Db4o.Db4oEmbedded.OpenFile(String databaseFileName)
   at dbo.Program.Main(String[] args) in /Users/x/Projects/dbo/dbo/Program.cs:line 46`

**Comment by iboxdb** [comment]
in Db4O without LockFile, only can be used in single thread.

```cs
var fc = Db4oEmbedded.NewConfiguration();
fc.File.LockDatabaseFile = false;
```
**Caution!**
[Db4objects.Db4o.Config.IFileConfiguration.LockDatabaseFile](https://iboxdb.github.io/db4o-gpl-doc/output/api/Db4objects.Db4o.Config/IFileConfiguration/1FAEB797)
